### PR TITLE
test: execute all test cases.

### PR DESCRIPTION
**Pull request by yoichiro**
Some test codes are currently not being executed with `npm run test`. This issue is critical for maintaining the quality of this library. This Pull Request adds the test files stored in the `src/functions/test` directory and the `src/models/test` directory to be executed with `npm run test`.

### CODE REVIEW

**Comment by yoichiro** [comment]
@yyyu-google Could you please review this pull request? Thank you in advance!

**Comment by yoichiro** [comment]
@yyyu-google This library has several test cases, but some of them are not being executed. As a result, the quality of this library is not being maintained at the expected level. This pull request includes fixes to ensure that all test cases are executed. Personally, I believe this fix is urgent to ensure the quality of this library. Please review and merge it as soon as possible.

**Comment by yyyu-google** [comment]
Thanks @yoichiro 
I requested @happy-qiao  to review. One comment: title should be `test: execute all test cases`.

**Comment by yoichiro** [comment]
@yyyu-google I updated the title.

**Review by happy-qiao — APPROVED** [review]

**Comment by yoichiro** [comment]
@happy-qiao Thank you for the reviewing.
@yyyu-google You can merge this pull request into the main branch.

**Pull request merged**
