### PR TITLE
feat: Add `ClientErrorApi` with `apiError` property containing error from API

### PR DESCRIPTION
**Pull request by tjenkinson**
refs #142

We'd like to access the actual error from the api so that we can determine what type of error it is. E.g. if it's a rate limit error we want to show a different message to if it's another type of error.

So this adds a `ClientErrorApi` error that extends `ClientError` and is thrown with the response error object if an api error occurs.

Whilst working on this also realised the tests weren't actually running 😱, so fixed that too.

### CODE REVIEW

**Review by happy-qiao — CHANGES_REQUESTED** [review]
Can you add a system test? I am not sure about the response error body data structure.

Thanks

**Comment by happy-qiao** [comment]
Hi @tjenkinson 

You can search ClientError in this file https://github.com/googleapis/nodejs-vertexai/blob/main/system_test/end_to_end_sample_test.ts#L20

Thanks

**Comment by happy-qiao** [comment]
@tjenkinson I have created https://github.com/tjenkinson/nodejs-vertexai/pull/1#issue-2491040782 in your forked repo. Please take a look and merge it in your forked repo and then it will show in this PR

**Comment by 0xthierry** [comment]
looking for this feature too 👀

**Comment by happy-qiao** [comment]
@tjenkinson To save turnaround time and release this feature as soon as possible, I created https://github.com/googleapis/nodejs-vertexai/pull/421 and referenced this PR in https://github.com/googleapis/nodejs-vertexai/pull/421. I will merge https://github.com/googleapis/nodejs-vertexai/pull/421 by end of today. If you have any concern, please reply by end of Aug 29. 

Thanks

**Pull request closed without merging**
